// Regenerates the auto-tracked block in PORTING.md (between the AUTO markers).
// Run by .github/workflows/update-porting.yml on every push to main, and can be
// run locally with: node scripts/update-porting.mjs
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const UPSTREAM = 'https://github.com/Jshort805/Games.git';
const UPSTREAM_BRANCH = 'main';
const FILE = 'PORTING.md';
const BEGIN = '<!-- AUTO:BEGIN -->';
const END = '<!-- AUTO:END -->';

// Run a shell command, returning trimmed stdout or '' on failure.
function sh(cmd) {
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
}

const sha = sh('git rev-parse --short HEAD');
const branch = sh('git rev-parse --abbrev-ref HEAD') || 'main';
const now = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

// Best-effort comparison against the original (upstream) repo.
sh('git remote remove upstream');
sh(`git remote add upstream ${UPSTREAM}`);
let fetched = false;
try {
  execSync(`git fetch --quiet upstream ${UPSTREAM_BRANCH}`, { stdio: 'ignore' });
  fetched = true;
} catch {
  fetched = false;
}

let workToPort;
if (fetched) {
  const ahead = sh(`git rev-list --count upstream/${UPSTREAM_BRANCH}..HEAD`);
  const log = sh(`git log --oneline --no-decorate upstream/${UPSTREAM_BRANCH}..HEAD`);
  const stat = sh(`git diff --stat upstream/${UPSTREAM_BRANCH}..HEAD`);
  workToPort =
`**Commits on this fork not yet in the original repo (\`${UPSTREAM_BRANCH}\`): ${ahead || '0'}**

\`\`\`
${log || '(in sync — nothing to port)'}
\`\`\`

**Files that differ from the original repo:**

\`\`\`
${stat || '(no differences)'}
\`\`\``;
} else {
  const log = sh('git log --oneline --no-decorate -30');
  workToPort =
`> Could not reach the original repo (\`${UPSTREAM}\`) from CI — it may be private.
> Showing this fork's 30 most recent commits instead (all candidates to port):

\`\`\`
${log}
\`\`\``;
}
sh('git remote remove upstream');

// Milestone commits, auto-detected from commit messages ("Phase …" / "milestone").
const milestones = sh('git log --oneline --no-decorate -i --grep="^Phase" --grep="milestone"');

// Inventory of the buildable project that actually needs porting.
const files = sh('git ls-files landgrab-collaborated');
const fileCount = files ? files.split('\n').length : 0;

const block =
`_Auto-generated by \`.github/workflows/update-porting.yml\` — do not edit between the AUTO markers._

- **Last updated:** ${now}
- **Fork position:** \`${branch}\` @ \`${sha}\`
- **Tracked files in \`landgrab-collaborated/\`:** ${fileCount}

### Work to port

${workToPort}

### Milestone commits (auto-detected)

\`\`\`
${milestones || '(none found yet)'}
\`\`\``;

let content = readFileSync(FILE, 'utf8');
const re = new RegExp(`${BEGIN}[\\s\\S]*?${END}`);
const replacement = `${BEGIN}\n${block}\n${END}`;
content = re.test(content) ? content.replace(re, replacement) : `${content}\n\n${replacement}\n`;
writeFileSync(FILE, content);
console.log('PORTING.md refreshed.');
